//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon_Internship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int pid { get; set; }
        public double amount { get; set; }
        public string cust_id { get; set; }
        public int res_id { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
